#############################################################
# This YAML section desribes a k8s PV for mongodb dbPath    #
#############################################################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-24cdc52d-aea2-11e7-9633-000d3a2b8d7c
spec:
  accessModes:
  - ReadWriteOnce
  azureDisk:
    cachingMode: None
    diskName: <Azure Disk Name>
    diskURI: <Azure Disk URL>
    fsType: ext4
    readOnly: false
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow-db
---
#############################################################
# This YAML section desribes a k8s PV  for mongodb configDB #
#############################################################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-24f49141-aea2-11e7-9633-000d3a2b8d7c
spec:
  accessModes:
  - ReadWriteOnce
  azureDisk:
    cachingMode: None
    diskName: <Azure Disk Name>
    diskURI: <Azure Disk URL>
    fsType: ext4
    readOnly: false
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow-configdb
