####################################################
# This config file runs rethinkdb:2.3 as a service #
####################################################

apiVersion: v1
kind: Service
metadata:
  name: rdb-service
  namespace: default
  labels:
    name: rdb-service
spec:
  selector:
    app: rdb
  ports:
  - port: 8080
    targetPort: 8080
    name: rethinkdb-api
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: StatefulSet 
metadata:
  name: rdb
  namespace: default
spec:
  serviceName: rdb
  replicas: 1
  template:
    metadata:
      name: rdb
      labels:
        app: rdb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: rethinkdb
        image: rethinkdb:2.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          hostPort: 8080
          name: rdb-port
          protocol: TCP 
        volumeMounts:
        - name: rdb-data
          mountPath: /data
        resources:
          limits:
            cpu: 200m
            memory: 768Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 10
      restartPolicy: Always
      volumes:
      - name: rdb-data
        hostPath:
          path: /disk/rdb-data
